"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.scrubber import DEFAULT_DENYLIST, EventScrubber

load_dotenv()

# Compartido con una Cloudflare Transform Rule que agrega X-Origin-Secret a cada
# request que pasa por el CDN. Sin esto, CF-Connecting-IP no es confiable
# (ver core.utils.get_client_ip).
CLOUDFLARE_SHARED_SECRET = os.getenv('CLOUDFLARE_SHARED_SECRET', '')

SENTRY_DSN = os.getenv('SENTRY_DSN', '')
if SENTRY_DSN:
    _default_sentry_env = 'production' if os.getenv('RAILWAY_ENVIRONMENT_ID') else 'development'
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        environment=os.getenv('SENTRY_ENVIRONMENT', _default_sentry_env),
        traces_sample_rate=float(os.getenv('SENTRY_TRACES_SAMPLE_RATE', '0.1')),
        send_default_pii=True,
        # send_default_pii adjunta IP/usuario a cada evento (lo queremos, para
        # forense). El denylist por defecto ya tapa password/token/etc; se
        # extiende con los campos propios del proyecto que igual son PII.
        event_scrubber=EventScrubber(denylist=DEFAULT_DENYLIST + ['rut', 'pin_kiosco', 'pin']),
    )

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-x$$*6k_#o7=-+nd03--kot7=v6w0059ejbtw+8*x-n1w!0bs7d')
                       
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

railway_domain = os.getenv('RAILWAY_PUBLIC_DOMAIN', 'sitrep-nav-production.up.railway.app')
allowed_hosts_env = os.getenv('ALLOWED_HOSTS', '')
extra_hosts = [h.strip() for h in allowed_hosts_env.split(',') if h.strip()]

_on_railway = bool(os.getenv('RAILWAY_ENVIRONMENT_ID'))

ALLOWED_HOSTS = [
    railway_domain,
    'localhost',
    '127.0.0.1',
    'healthcheck.railway.app'
] + extra_hosts

railway_private_domain = os.getenv('RAILWAY_PRIVATE_DOMAIN', '')
if railway_private_domain:
    ALLOWED_HOSTS.append(railway_private_domain)

CSRF_TRUSTED_ORIGINS = [
    f'https://{railway_domain}',
] + [f'https://{h}' for h in extra_hosts]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_vite',
    'sitrep.accounts',
    'sitrep.fleet',
    'sitrep.catalog',
    'sitrep.inspection',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'sitrep.accounts.middleware.TenantMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'frontend' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///' + str(BASE_DIR / 'db.sqlite3'),
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

DJANGO_VITE = {
    'default': {
        'dev_mode': DEBUG,
        'dev_server_port': 5173,
        'manifest_path': BASE_DIR / 'static' / 'dist' / '.vite' / 'manifest.json',
        'static_url_prefix': '' if DEBUG else 'dist',
    }
}

# Inyección del Custom User Model para soporte Multi-Tenant
AUTH_USER_MODEL = 'accounts.Usuario'

AUTHENTICATION_BACKENDS = [
    'sitrep.accounts.backends.WebTenantBackend',
    'sitrep.accounts.backends.KioscoTenantBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Proxy SSL (Cloudflare)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# Correo saliente vía Resend (SMTP relay, dominio sitrep.cl ya verificado ahí).
# En DEBUG se imprime en consola en vez de mandar de verdad.
EMAIL_BACKEND = (
    'django.core.mail.backends.console.EmailBackend' if DEBUG
    else 'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_HOST = 'smtp.resend.com'
# 587 daba TimeoutError en Railway (probable bloqueo de puerto del proveedor).
# 2587 es el puerto alterno STARTTLS que Resend publica para este caso.
EMAIL_PORT = 2587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'resend'
EMAIL_HOST_PASSWORD = os.getenv('RESEND_API_KEY', '')
# Sin esto smtplib bloquea indefinidamente si Resend no responde, y con
# gunicorn --timeout 120 --workers 2 eso puede tumbar el sitio entero.
EMAIL_TIMEOUT = 10
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'SITREP <no-reply@sitrep.cl>')
CONTACT_EMAIL_TO = os.getenv('CONTACT_EMAIL_TO', 'contacto@sitrep.cl')

# Cloudflare Turnstile
TURNSTILE_SITE_KEY = os.getenv('TURNSTILE_SITE_KEY', '')
TURNSTILE_SECRET_KEY = os.getenv('TURNSTILE_SECRET_KEY', '')
