# Generated by Django 6.0.2 on 2026-07-08 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('rol', models.CharField(blank=True, max_length=20)),
                ('accion', models.CharField(choices=[('read', 'Lectura'), ('export', 'Exportación'), ('write', 'Escritura')], max_length=10)),
                ('recurso', models.CharField(max_length=100)),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('endpoint', models.CharField(blank=True, max_length=255)),
                ('naviera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.naviera')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['usuario', 'created_at'], name='accounts_au_usuario_18728a_idx')],
            },
        ),
    ]
