# Generated by Django 6.0.2 on 2026-07-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auditevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='naviera',
            name='catalogo_independiente',
            field=models.BooleanField(default=False, help_text='Si es True, esta naviera ignora el catálogo central: solo ve recursos scoped a ella o a sus naves.'),
        ),
    ]
