# Generated by Django 6.0.2 on 2026-07-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_naviera_catalogo_independiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='accion',
            field=models.CharField(choices=[('read', 'Lectura'), ('export', 'Exportación'), ('write', 'Escritura'), ('blocked', 'Bloqueado')], max_length=10),
        ),
    ]
