# Generated by Django 6.0.5 on 2026-06-29 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nombre_tecnico', models.CharField(blank=True, max_length=100, null=True)),
                ('orden', models.PositiveSmallIntegerField(blank=True, help_text='Orden de visualización del área. Basado en el primer dígito del código de sus recursos.', null=True)),
                ('token_color', models.CharField(blank=True, help_text="Identificador para la paleta del cliente en el frontend (ej: 'salvamento', 'cubierta')", max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Periodicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('duracion_dias', models.PositiveIntegerField(default=30, help_text='Duración del período en días. Ej: 7 para semanal, 30 para mensual.')),
                ('offset_dias', models.PositiveIntegerField(default=1, help_text='Días de margen tras fecha_termino antes de vencer el período. Ej: 1 para semanal, 3 para mensual.')),
                ('responsabilidad', models.CharField(choices=[('mar', 'Mar'), ('tierra', 'Tierra'), ('todos', 'Todos'), ('ninguno', 'Ninguno')], max_length=20)),
                ('visibilidad', models.CharField(choices=[('mar', 'Mar'), ('tierra', 'Tierra'), ('todos', 'Todos'), ('ninguno', 'Ninguno')], max_length=20)),
            ],
            options={
                'verbose_name': 'Periodicidad',
                'verbose_name_plural': 'Periodicidades',
            },
        ),
        migrations.CreateModel(
            name='Proposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Seguridad', 'Seguridad'), ('Operacional', 'Operacional')], max_length=50)),
                ('tipo', models.CharField(choices=[('Documentacion', 'Documentación'), ('Material', 'Material')], max_length=50)),
            ],
            options={
                'verbose_name': 'Propósito',
                'verbose_name_plural': 'Propósitos',
            },
        ),
        migrations.CreateModel(
            name='Nave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=30)),
                ('eslora', models.DecimalField(decimal_places=2, max_digits=6)),
                ('arqueo_bruto', models.IntegerField()),
                ('capacidad_personas', models.IntegerField()),
                ('is_active', models.BooleanField(default=True, help_text='Si es False, la nave fue vendida o dada de baja')),
                ('agregado_en', models.DateTimeField(auto_now_add=True)),
                ('naviera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.naviera')),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Tablet Puente Mando, PC Sala Máquinas', max_length=100)),
                ('token_hash', models.CharField(blank=True, help_text='Hash criptográfico del token físico', max_length=128, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Apagar si la tablet se pierde o se daña')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('naviera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='accounts.naviera')),
                ('nave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='inventory.nave')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('operativo', 'Operativo'), ('observado', 'Observado'), ('fallido', 'Fallido'), ('omitido', 'Omitido'), ('caduco', 'Caduco')], default='pendiente', max_length=20)),
                ('nave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='inventory.nave')),
                ('periodicidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.periodicidad')),
            ],
            options={
                'verbose_name': 'Periodo de Revisión',
                'verbose_name_plural': 'Periodos de Revisión',
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(blank=True, help_text='Código del recurso según la documentación del cliente (ej: 3.3-Q).', max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción extendida del recurso. Separada del nombre para nombres limpios.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del recurso. Usada para excluir recursos del historial de períodos anteriores a su creación.')),
                ('requerimientos', models.JSONField(default=list, help_text='Ej: ["ser naranjo", "tener cintas"]')),
                ('regla_aplicacion', models.JSONField(blank=True, help_text='Reglas para atributos dinámicos', null=True)),
                ('area', models.ForeignKey(blank=True, help_text='Área operacional a la que pertenece el recurso (ej: Salvamento, Incendio).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos', to='inventory.area')),
                ('naviera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recursos_privados', to='accounts.naviera')),
                ('periodicidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.periodicidad')),
                ('proposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.proposito')),
            ],
        ),
        migrations.CreateModel(
            name='MatrizNaveRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('es_visible', models.BooleanField(default=True)),
                ('modificado_manualmente', models.BooleanField(default=False)),
                ('ultimo_estado_operativo', models.BooleanField(blank=True, default=None, help_text='Último estado operativo confirmado para este recurso en esta nave. None = nunca declarado. True = operativo. False = fallado. Solo se actualiza cuando estado_operativo is not None (no en guardados parciales).', null=True)),
                ('ultimo_estado_operativo_en', models.DateTimeField(blank=True, default=None, help_text='Timestamp de la última vez que ultimo_estado_operativo fue actualizado.', null=True)),
                ('es_fallo_nuevo', models.BooleanField(default=False, help_text='True si el recurso pasó de operativo/pendiente a fallado en el período actual. Se resetea al cerrar el período.')),
                ('ultimo_estado_operativo_anterior', models.BooleanField(blank=True, default=None, help_text='Snapshot de ultimo_estado_operativo al momento del último cierre de período. Se actualiza solo al cerrar período, nunca al guardar fichas individuales. Usado para determinar si un fallo es nuevo comparando contra el estado del período anterior.', null=True)),
                ('nave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriz_recursos', to='inventory.nave')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.recurso')),
            ],
            options={
                'verbose_name': 'Matriz Nave-Recurso',
                'verbose_name_plural': 'Matriz Nave-Recurso',
            },
        ),
        migrations.CreateModel(
            name='FichaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision', models.DateTimeField(auto_now_add=True)),
                ('estado_ficha', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('completa', 'Completa')], default='en_progreso', help_text='Estado de completitud de la ficha independiente del resultado operativo.', max_length=20)),
                ('estado_operativo', models.BooleanField(default=None, help_text='None=sin determinar, True=operativo, False=con falla. Solo se asigna cuando la ficha está completa.', null=True)),
                ('observacion_general', models.TextField(blank=True, default='')),
                ('payload_checklist', models.JSONField(default=dict)),
                ('modificado_en', models.DateTimeField(blank=True, help_text='Timestamp de la última modificación.', null=True)),
                ('modificado_por', models.ForeignKey(blank=True, help_text='Usuario que realizó la última modificación. Null si nunca fue modificada.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fichas_modificadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='inventory.periodorevision')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.recurso')),
            ],
            options={
                'verbose_name': 'Ficha de Registro',
                'verbose_name_plural': 'Fichas de Registro',
            },
        ),
        migrations.CreateModel(
            name='Tripulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('nave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripulantes', to='inventory.nave')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_naves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tripulación',
                'verbose_name_plural': 'Tripulaciones',
            },
        ),
        migrations.AddConstraint(
            model_name='nave',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('naviera', 'matricula'), name='unica_matricula_activa_por_naviera'),
        ),
        migrations.AlterUniqueTogether(
            name='matriznaverecurso',
            unique_together={('nave', 'recurso')},
        ),
        migrations.AlterUniqueTogether(
            name='ficharegistro',
            unique_together={('periodo', 'recurso')},
        ),
        migrations.AlterUniqueTogether(
            name='tripulacion',
            unique_together={('usuario', 'nave')},
        ),
    ]
