# Generated by Django 6.0.2 on 2026-02-24 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('responsabilidad', models.CharField(choices=[('mar', 'Mar'), ('tierra', 'Tierra')], max_length=20)),
                ('visibilidad', models.CharField(choices=[('mar', 'Mar'), ('tierra', 'Tierra')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Seguridad', 'Seguridad'), ('Operacional', 'Operacional')], max_length=50)),
                ('tipo', models.CharField(choices=[('Documentacion', 'Documentación'), ('Material', 'Material')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=30)),
                ('eslora', models.DecimalField(decimal_places=2, max_digits=6)),
                ('arqueo_bruto', models.IntegerField()),
                ('capacidad_personas', models.IntegerField()),
                ('is_active', models.BooleanField(default=True, help_text='Si es False, la nave fue vendida o dada de baja')),
                ('agregado_en', models.DateTimeField(auto_now_add=True)),
                ('naviera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.naviera')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado'), ('vencido', 'Vencido')], default='abierto', max_length=20)),
                ('nave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='inventory.nave')),
                ('periodicidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.periodicidad')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('requerimientos', models.JSONField(default=list, help_text='Ej: ["ser naranjo", "tener cintas"]')),
                ('regla_aplicacion', models.JSONField(blank=True, help_text='Reglas para atributos dinámicos', null=True)),
                ('naviera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recursos_privados', to='inventory.naviera')),
                ('periodicidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.periodicidad')),
                ('proposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.proposito')),
            ],
        ),
        migrations.CreateModel(
            name='MatrizNaveRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('es_visible', models.BooleanField(default=True)),
                ('modificado_manualmente', models.BooleanField(default=False)),
                ('nave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriz_recursos', to='inventory.nave')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='FichaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision', models.DateTimeField(auto_now_add=True)),
                ('estado_operativo', models.BooleanField()),
                ('observacion_general', models.TextField(blank=True, default='')),
                ('payload_checklist', models.JSONField(default=dict)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='inventory.periodorevision')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='Tripulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('nave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripulantes', to='inventory.nave')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_naves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='nave',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('naviera', 'matricula'), name='unica_matricula_activa_por_naviera'),
        ),
        migrations.AlterUniqueTogether(
            name='matriznaverecurso',
            unique_together={('nave', 'recurso')},
        ),
        migrations.AlterUniqueTogether(
            name='ficharegistro',
            unique_together={('periodo', 'recurso')},
        ),
        migrations.AlterUniqueTogether(
            name='tripulacion',
            unique_together={('usuario', 'nave')},
        ),
    ]
