# Generated by Django 6.0.2 on 2026-02-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_periodicidad_proposito_nave_periodorevision_recurso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ficharegistro',
            options={'verbose_name': 'Ficha de Registro', 'verbose_name_plural': 'Fichas de Registro'},
        ),
        migrations.AlterModelOptions(
            name='matriznaverecurso',
            options={'verbose_name': 'Matriz Nave-Recurso', 'verbose_name_plural': 'Matriz Nave-Recurso'},
        ),
        migrations.AlterModelOptions(
            name='periodicidad',
            options={'verbose_name': 'Periodicidad', 'verbose_name_plural': 'Periodicidades'},
        ),
        migrations.AlterModelOptions(
            name='periodorevision',
            options={'verbose_name': 'Periodo de Revisión', 'verbose_name_plural': 'Periodos de Revisión'},
        ),
        migrations.AlterModelOptions(
            name='proposito',
            options={'verbose_name': 'Propósito', 'verbose_name_plural': 'Propósitos'},
        ),
        migrations.AlterModelOptions(
            name='tripulacion',
            options={'verbose_name': 'Tripulación', 'verbose_name_plural': 'Tripulaciones'},
        ),
        migrations.AlterField(
            model_name='periodicidad',
            name='responsabilidad',
            field=models.CharField(choices=[('mar', 'Mar'), ('tierra', 'Tierra'), ('todos', 'Todos'), ('ninguno', 'Ninguno')], max_length=20),
        ),
        migrations.AlterField(
            model_name='periodicidad',
            name='visibilidad',
            field=models.CharField(choices=[('mar', 'Mar'), ('tierra', 'Tierra'), ('todos', 'Todos'), ('ninguno', 'Ninguno')], max_length=20),
        ),
    ]
