# Generated by Django 6.0.2 on 2026-02-27 05:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_ficharegistro_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Tablet Puente Mando, PC Sala Máquinas', max_length=100)),
                ('token_autorizacion', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Apagar si la tablet se pierde o se daña')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='inventory.nave')),
                ('naviera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='inventory.naviera')),
            ],
        ),
    ]
