# Generated by Django 6.0.2 on 2026-02-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_dispositivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pin_kiosco',
            field=models.CharField(blank=True, help_text='PIN cifrado para acceso en Kiosco', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin_sitrep', 'Admin SITREP'), ('admin_naviera', 'Admin Naviera'), ('capitan', 'Admin Nave'), ('tierra', 'Tierra'), ('mar', 'Mar')], default='mar', max_length=20),
        ),
    ]
