# Generated by Django 6.0.2 on 2026-02-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_usuario_pin_kiosco_alter_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='token_autorizacion',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='token_hash',
            field=models.CharField(blank=True, help_text='Hash criptográfico del token físico', max_length=128, null=True),
        ),
    ]
