# Generated by Django 6.0.2 on 2026-02-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_dispositivo_token_autorizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='naviera',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador único para la URL (ej. transmarko)', null=True, unique=True),
        ),
    ]
