# Generated by Django 6.0.2 on 2026-04-12 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_naviera_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='nave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='inventory.nave'),
        ),
    ]
