# Generated by Django 6.0.2 on 2026-04-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_dispositivo_nave'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicidad',
            name='duracion_dias',
            field=models.PositiveIntegerField(default=30, help_text='Duración del período en días. Ej: 7 para semanal, 30 para mensual.'),
        ),
    ]
