# Generated by Django 6.0.2 on 2026-04-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_periodicidad_duracion_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicidad',
            name='offset_dias',
            field=models.PositiveIntegerField(default=1, help_text='Días de margen tras fecha_termino antes de vencer el período. Ej: 1 para semanal, 3 para mensual.'),
        ),
    ]
