# Generated by Django 6.0.2 on 2026-04-20 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_periodicidad_offset_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficharegistro',
            name='modificado_en',
            field=models.DateTimeField(blank=True, help_text='Timestamp de la última modificación.', null=True),
        ),
        migrations.AddField(
            model_name='ficharegistro',
            name='modificado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última modificación. Null si nunca fue modificada.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fichas_modificadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
