# Generated by Django 6.0.2 on 2026-04-23 23:31

from django.db import migrations, models


def _normalizar_payload_checklist(payload_checklist):
    if not isinstance(payload_checklist, dict):
        return {}

    payload_normalizado = {}
    for requerimiento, valor in payload_checklist.items():
        if isinstance(valor, dict):
            payload_normalizado[requerimiento] = dict(valor)
        elif isinstance(valor, bool):
            payload_normalizado[requerimiento] = {"cumple": valor}
        else:
            payload_normalizado[requerimiento] = valor
    return payload_normalizado


def _ficha_esta_completa(ficha):
    payload_checklist = _normalizar_payload_checklist(ficha.payload_checklist or {})
    requerimientos = ficha.recurso.requerimientos or []
    if ficha.estado_operativo is None:
        return False
    if not requerimientos:
        return True

    return all(
        isinstance(payload_checklist.get(requerimiento), dict)
        and "cumple" in payload_checklist.get(requerimiento)
        for requerimiento in requerimientos
    )


def _determinar_estado_nuevo(periodo, matrices, fichas):
    total_recursos = len(matrices)
    fichas_completas = [ficha for ficha in fichas if _ficha_esta_completa(ficha)]

    if total_recursos == len(fichas_completas):
        if any(ficha.estado_operativo is False for ficha in fichas_completas):
            return "fallido"
        if any((ficha.observacion_general or "").strip() for ficha in fichas_completas):
            return "observado"
        return "conforme"

    if not fichas_completas:
        if not fichas:
            return "omitido"
        return "caduco"

    if len(fichas_completas) < total_recursos:
        return "caduco"

    if len(fichas_completas) == total_recursos:
        if any(ficha.estado_operativo is False for ficha in fichas_completas):
            return "fallido"
        if any((ficha.observacion_general or "").strip() for ficha in fichas_completas):
            return "observado"
        return "conforme"

    return "caduco"


def migrar_estados_periodos(apps, schema_editor):
    PeriodoRevision = apps.get_model("inventory", "PeriodoRevision")
    FichaRegistro = apps.get_model("inventory", "FichaRegistro")
    MatrizNaveRecurso = apps.get_model("inventory", "MatrizNaveRecurso")

    for ficha in FichaRegistro.objects.all().iterator():
        payload_normalizado = _normalizar_payload_checklist(ficha.payload_checklist)
        if payload_normalizado != (ficha.payload_checklist or {}):
            FichaRegistro.objects.filter(pk=ficha.pk).update(payload_checklist=payload_normalizado)

    for periodo in PeriodoRevision.objects.all().iterator():
        if periodo.estado == "abierto":
            PeriodoRevision.objects.filter(pk=periodo.pk).update(estado="pendiente")
            continue

        matrices = list(
            MatrizNaveRecurso.objects.filter(
                nave_id=periodo.nave_id,
                es_visible=True,
                recurso__periodicidad_id=periodo.periodicidad_id,
            ).select_related("recurso")
        )
        recurso_ids = [matriz.recurso_id for matriz in matrices]
        fichas = list(
            FichaRegistro.objects.filter(
                periodo_id=periodo.id,
                recurso_id__in=recurso_ids,
            ).select_related("recurso")
        )
        nuevo_estado = _determinar_estado_nuevo(periodo, matrices, fichas)
        PeriodoRevision.objects.filter(pk=periodo.pk).update(estado=nuevo_estado)


def revertir_estados_periodos(apps, schema_editor):
    PeriodoRevision = apps.get_model("inventory", "PeriodoRevision")
    FichaRegistro = apps.get_model("inventory", "FichaRegistro")

    PeriodoRevision.objects.filter(estado__in=["pendiente", "en_proceso"]).update(estado="abierto")
    PeriodoRevision.objects.filter(estado__in=["conforme", "observado", "fallido"]).update(
        estado="cerrado"
    )
    PeriodoRevision.objects.filter(estado__in=["omitido", "caduco"]).update(estado="vencido")

    for ficha in FichaRegistro.objects.all().iterator():
        payload_checklist = ficha.payload_checklist or {}
        payload_revertido = {}
        for requerimiento, valor in payload_checklist.items():
            if isinstance(valor, dict) and set(valor.keys()) == {"cumple"}:
                payload_revertido[requerimiento] = valor.get("cumple")
            else:
                payload_revertido[requerimiento] = valor

        if payload_revertido != payload_checklist:
            FichaRegistro.objects.filter(pk=ficha.pk).update(payload_checklist=payload_revertido)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_ficharegistro_modificado_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficharegistro',
            name='estado_operativo',
            field=models.BooleanField(default=None, help_text='None=sin determinar, True=operativo, False=con falla. Solo se asigna cuando la ficha está completa.', null=True),
        ),
        migrations.AlterField(
            model_name='periodorevision',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('conforme', 'Conforme'), ('observado', 'Observado'), ('fallido', 'Fallido'), ('omitido', 'Omitido'), ('caduco', 'Caduco')], default='pendiente', max_length=20),
        ),
        migrations.RunPython(migrar_estados_periodos, revertir_estados_periodos),
    ]
