# Generated by Django 6.0.2 on 2026-04-27 00:00

from django.db import migrations, models


def _normalizar_payload_checklist(payload_checklist):
    if not isinstance(payload_checklist, dict):
        return {}

    payload_normalizado = {}
    for requerimiento, valor in payload_checklist.items():
        if isinstance(valor, dict):
            item_normalizado = dict(valor)
            if "cumple" in item_normalizado and "observacion" not in item_normalizado:
                item_normalizado["observacion"] = ""
            payload_normalizado[requerimiento] = item_normalizado
        elif isinstance(valor, bool):
            payload_normalizado[requerimiento] = {
                "cumple": valor,
                "observacion": "",
            }
        else:
            payload_normalizado[requerimiento] = valor
    return payload_normalizado


def _es_ficha_completa(ficha):
    if ficha.estado_operativo is None:
        return False

    requerimientos = ficha.recurso.requerimientos or []
    if not requerimientos:
        return True

    payload_checklist = _normalizar_payload_checklist(ficha.payload_checklist or {})
    for requerimiento in requerimientos:
        item = payload_checklist.get(requerimiento)
        if not isinstance(item, dict) or "cumple" not in item:
            return False

    return True


def backfill_estado_ficha(apps, schema_editor):
    FichaRegistro = apps.get_model("inventory", "FichaRegistro")

    for ficha in FichaRegistro.objects.select_related("recurso").all().iterator():
        estado_ficha = "completa" if _es_ficha_completa(ficha) else "en_progreso"
        if ficha.estado_ficha != estado_ficha:
            FichaRegistro.objects.filter(pk=ficha.pk).update(estado_ficha=estado_ficha)


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_alter_ficharegistro_estado_operativo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Área",
                "verbose_name_plural": "Áreas",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="ficharegistro",
            name="estado_ficha",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("en_progreso", "En progreso"),
                    ("completa", "Completa"),
                ],
                default="en_progreso",
                help_text=(
                    "Estado de completitud de la ficha independiente del resultado operativo."
                ),
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recurso",
            name="area",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Área operacional a la que pertenece el recurso "
                    "(ej: Salvamento, Incendio)."
                ),
                null=True,
                on_delete=models.SET_NULL,
                related_name="recursos",
                to="inventory.area",
            ),
        ),
        migrations.RunPython(backfill_estado_ficha, migrations.RunPython.noop),
    ]
