# Generated by Django 6.0.2 on 2026-04-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_alter_ficharegistro_estado_operativo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Área",
                "verbose_name_plural": "Áreas",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="recurso",
            name="area",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Área operacional a la que pertenece el recurso "
                    "(ej: Salvamento, Incendio)."
                ),
                null=True,
                on_delete=models.SET_NULL,
                related_name="recursos",
                to="inventory.area",
            ),
        ),
    ]
