# Generated by Django 6.0.2 on 2026-04-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_area_recurso_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="ficharegistro",
            name="estado_ficha",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("en_progreso", "En progreso"),
                    ("completa", "Completa"),
                ],
                default="en_progreso",
                help_text=(
                    "Estado de completitud de la ficha independiente del resultado operativo."
                ),
                max_length=20,
            ),
        ),
    ]
