# Generated by Django 6.0.2 on 2026-04-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_ficharegistro_estado_ficha'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='nombre_tecnico',
            field=models.CharField(default='sin_nombre', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='area',
            name='token_color',
            field=models.CharField(blank=True, help_text="Identificador para la paleta del cliente en el frontend (ej: 'salvamento', 'cubierta')", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='periodorevision',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('conforme', 'Conforme'), ('observado', 'Observado'), ('fallido', 'Fallido'), ('omitido', 'Omitido'), ('caduco', 'Caduco')], default='pendiente', max_length=20),
        ),
    ]
