# Generated by Django 6.0.2 on 2026-04-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_area_nombre_tecnico_area_token_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriznaverecurso',
            name='ultimo_estado_operativo',
            field=models.BooleanField(blank=True, default=None, help_text='Último estado operativo confirmado para este recurso en esta nave. None = nunca declarado. True = operativo. False = fallado. Solo se actualiza cuando estado_operativo is not None (no en guardados parciales).', null=True),
        ),
        migrations.AddField(
            model_name='matriznaverecurso',
            name='ultimo_estado_operativo_en',
            field=models.DateTimeField(blank=True, default=None, help_text='Timestamp de la última vez que ultimo_estado_operativo fue actualizado.', null=True),
        ),
    ]
