# Generated by Django 6.0.2 on 2026-04-30 00:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_matriznaverecurso_ultimo_estado_operativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha de creación del recurso. Usada para excluir recursos del historial de períodos anteriores a su creación.'),
            preserve_default=False,
        ),
    ]
