# Generated by Django 6.0.2 on 2026-05-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_backfill_recurso_created_at_to_20200101'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código del recurso según la documentación del cliente (ej: 3.3-Q).', max_length=50, null=True),
        ),
    ]
