# Generated by Django 6.0.2 on 2026-05-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_recurso_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción extendida del recurso. Separada del nombre para nombres limpios.', null=True),
        ),
    ]
