# Generated by Django 6.0.2 on 2026-05-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_recurso_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='orden',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Orden de visualización del área. Basado en el primer dígito del código de sus recursos.', null=True),
        ),
    ]
