# Generated by Django 6.0.2 on 2026-05-27 18:27

from django.db import migrations, models


def inicializar_estado_anterior(apps, schema_editor):
    MatrizNaveRecurso = apps.get_model('inventory', 'MatrizNaveRecurso')
    MatrizNaveRecurso.objects.update(
        ultimo_estado_operativo_anterior=models.F('ultimo_estado_operativo')
    )


def revertir(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_area_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Área', 'verbose_name_plural': 'Áreas'},
        ),
        migrations.AddField(
            model_name='matriznaverecurso',
            name='es_fallo_nuevo',
            field=models.BooleanField(default=False, help_text='True si el recurso pasó de operativo/pendiente a fallado en el período actual. Se resetea al cerrar el período.'),
        ),
        migrations.AddField(
            model_name='matriznaverecurso',
            name='ultimo_estado_operativo_anterior',
            field=models.BooleanField(blank=True, default=None, help_text='Snapshot de ultimo_estado_operativo al momento del último cierre de período. Se actualiza solo al cerrar período, nunca al guardar fichas individuales. Usado para determinar si un fallo es nuevo comparando contra el estado del período anterior.', null=True),
        ),
        migrations.RunPython(inicializar_estado_anterior, revertir),
    ]
