# Generated by Django 6.0.2 on 2026-07-10 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_recurso_requerimientos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='naviera',
        ),
    ]
