# Generated by Django 6.0.2 on 2026-07-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_recurso_naviera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='regla_aplicacion',
            field=models.JSONField(blank=True, help_text='Motor de reglas: calcula, por nave, tanto la CANTIDAD del requerimiento "cantidad" como la VISIBILIDAD del recurso (es_visible en la matriz). Ej: {"atributo": "eslora", "condiciones": [{"operador": "<=", "valor": 10, "resultado_cantidad": 0, "resultado_visible": false}], "fallback_cantidad": 2, "fallback_visible": true}. Sin regla (null): cantidad=0 y es_visible=True para toda nave.', null=True),
        ),
    ]
