# Generated by Django 6.0.2 on 2026-07-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_recurso_regla_aplicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='regla_aplicacion',
            field=models.JSONField(blank=True, help_text='Motor de reglas: calcula, por nave, tanto la CANTIDAD del requerimiento "cantidad" como la VISIBILIDAD del recurso (es_visible en la matriz). Ej: {"version": 1, "atributo": "eslora", "condiciones": [{"operador": "<=", "valor": 10, "resultado_cantidad": 0, "resultado_visible": false}], "fallback_cantidad": 2, "fallback_visible": true}. "version" es opcional (se asume 1 si falta) — existe para que futuras versiones del motor no rompan reglas viejas. Sin regla (null): cantidad=0 y es_visible=True para toda nave.', null=True),
        ),
    ]
