# Generated by Django 6.0.2 on 2026-07-11 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_naviera_catalogo_independiente'),
        ('catalog', '0006_alter_recurso_regla_aplicacion'),
        ('fleet', '0002_nave_catalogo_independiente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Secuencia independiente por scope (central / naviera / nave), empieza en 1.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nota', models.TextField(blank=True, default='')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Null: sin editor asignado (no existe rol editor todavía).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogo_versiones_creadas', to=settings.AUTH_USER_MODEL)),
                ('nave', models.ForeignKey(blank=True, help_text='Null = esta versión no es de una nave específica (central o naviera).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versiones_catalogo', to='fleet.nave')),
                ('naviera', models.ForeignKey(blank=True, help_text='Null = cadena central. Si nave está seteado, naviera se deriva de nave.naviera.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versiones_catalogo', to='accounts.naviera')),
            ],
            options={
                'verbose_name': 'Versión de Catálogo',
                'verbose_name_plural': 'Versiones de Catálogo',
                'ordering': ['naviera_id', 'nave_id', 'numero'],
                'constraints': [models.UniqueConstraint(fields=('naviera', 'nave', 'numero'), name='unica_numero_por_scope_catalogo', nulls_distinct=False)],
            },
        ),
    ]
