# Generated by Django 6.0.2 on 2026-07-11 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_naviera_catalogo_independiente'),
        ('catalog', '0007_catalogoversion'),
        ('fleet', '0002_nave_catalogo_independiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='activo',
            field=models.BooleanField(default=True, help_text="False = esta versión de la lineage está 'eliminada'. Nunca se hace DELETE físico."),
        ),
        migrations.AddField(
            model_name='recurso',
            name='catalogo_version',
            field=models.ForeignKey(blank=True, help_text='Versión/scope-chain en la que esta fila exacta fue introducida.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recursos', to='catalog.catalogoversion'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='linaje_raiz',
            field=models.ForeignKey(blank=True, help_text='Null = esta fila ES la raíz de su lineage. Seteado = apunta a la fila raíz que agrupa todas las versiones/overrides históricos de este mismo concepto.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.recurso'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='nave',
            field=models.ForeignKey(blank=True, help_text='Seteado = override/independiente de esta nave específica. naviera se deriva de nave.naviera.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recursos_override', to='fleet.nave'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='naviera',
            field=models.ForeignKey(blank=True, help_text='Null = catálogo central. Seteado = override/independiente de esta naviera.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recursos_override', to='accounts.naviera'),
        ),
        migrations.AddConstraint(
            model_name='recurso',
            constraint=models.CheckConstraint(condition=models.Q(('nave__isnull', True), ('naviera__isnull', False), _connector='OR'), name='recurso_nave_implica_naviera'),
        ),
    ]
