# Generated by Django 6.0.2 on 2026-07-11 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_backfill_catalogo_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='catalogo_version',
            field=models.ForeignKey(help_text='Versión/scope-chain en la que esta fila exacta fue introducida.', on_delete=django.db.models.deletion.PROTECT, related_name='recursos', to='catalog.catalogoversion'),
        ),
    ]
