# Generated by Django 6.0.2 on 2026-07-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_recurso_categoria_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='requerimientos',
            field=models.JSONField(default=list, help_text='Lista de requerimientos tipados. Ej: [{"id": "vigencia", "tipo": "estandar", "texto": "Vigencia vigente"}, {"id": "condicion_1", "tipo": "condicion"}, {"id": "__cantidad__", "tipo": "cantidad"}]. Tipos: "estandar" (texto fijo del editor), "condicion" (label fijo "Condición."), "cantidad" (label calculado por el motor de reglas, sin texto), "empty" (label fijo "Verificación.", para recursos de documentación sin condición/cantidad).'),
        ),
    ]
