# Generated by Django 6.0.2 on 2026-07-07 16:26

from django.db import migrations, models


def colapsar_estados(apps, schema_editor):
    PeriodoRevision = apps.get_model('inventory', 'PeriodoRevision')
    PeriodoRevision.objects.filter(estado__in=['operativo', 'observado', 'fallido']).update(estado='cumplido')
    PeriodoRevision.objects.filter(estado__in=['omitido', 'caduco']).update(estado='vencido')


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_catalog_split'),
    ]

    operations = [
        migrations.RunPython(colapsar_estados, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='periodorevision',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('cumplido', 'Cumplido'), ('vencido', 'Vencido')], default='pendiente', max_length=20),
        ),
    ]
