# Generated by Django 6.0.2 on 2026-07-10 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_fix_en_progreso_periodos_cerrados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriznaverecurso',
            name='modificado_manualmente',
        ),
    ]
