# Generated by Django 6.0.2 on 2026-07-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_matriznaverecurso_modificado_manualmente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficharegistro',
            name='definicion_checklist',
            field=models.JSONField(blank=True, default=None, help_text='Snapshot del checklist (mismo shape que MotorFichas.construir_definicion_checklist) tomado al crear la ficha. Congela qué requerimientos aplican y sus labels para que la ficha no cambie si el catálogo cambia después. None = ficha anterior a este campo; usa el catálogo en vivo como fallback.', null=True),
        ),
    ]
