# Generated by Django 6.0.2 on 2026-07-11 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_recurso_catalogo_version_notnull'),
        ('inventory', '0008_periodorevision_catalogo_version_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodorevision',
            name='catalogo_version_central',
            field=models.ForeignKey(blank=True, help_text='Versión central vigente al crear este período. Null si el catálogo era independiente en ese momento. Capturado para reconstrucción histórica futura; nada en la app lo lee todavía.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.catalogoversion'),
        ),
        migrations.AlterField(
            model_name='periodorevision',
            name='catalogo_version_nave',
            field=models.ForeignKey(blank=True, help_text='Versión del override de la nave vigente al crear este período. Null si la nave nunca tuvo overrides. Capturado para reconstrucción histórica futura; nada en la app lo lee todavía.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.catalogoversion'),
        ),
        migrations.AlterField(
            model_name='periodorevision',
            name='catalogo_version_naviera',
            field=models.ForeignKey(blank=True, help_text='Versión del override de la naviera vigente al crear este período. Null si la naviera nunca tuvo overrides. Capturado para reconstrucción histórica futura; nada en la app lo lee todavía.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.catalogoversion'),
        ),
    ]
