# Generated by Django 6.0.2 on 2026-07-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nave',
            name='catalogo_independiente',
            field=models.BooleanField(default=False, help_text='Si es True (o si su naviera lo es), esta nave ignora el catálogo central.'),
        ),
    ]
